- name: Join domain
  hosts: windows_workstation
  gather_facts: no
  vars_prompt: 
  - name: domainadm
    prompt: what is the domain andministrator login
    private: no

  - name: domainpass
    prompt: what is the password for the account
    private: yes

  tasks:
    - name: Configure Primary DNS Server
      win_dns_client:
        adapter_names: "{{ device }}"
        ipv4_addresses: "10.0.5.5"
  
    - name: Join to the domain
      win_domain_membership:
        dns_domain_name: "blue12"
        hostname: "{{ hostname }}"
        domain_admin_user: "{{ domainadm }}"
        domain_admin_password: "{{ domainpass }}"
        domain_ou_path: "OU=workstations, OU=computers, OU=blue12, dc=blue12, dc=local"
        state: domain
      register: domain_state

    - name: reboot if needed
      win_reboot:
      when: domain_state.reboot_required

        





