- name: ubuntu-networking
  hosts: ubuntu_server
  tasks:
    - name: set host name
      hostname: 
        name: "{{hostname}}"
      become: yes

    - name: add host to hosts file
      lineinfile:
        path: /etc/hosts
        line: '127.0.1.1 {{hostname}}'
      become: yes

    - name: push over the networking script
      template:
        src: files/ubuntu/Wired connection 1.nmconnection
        dest: '/etc/NetworkManager/system-connections/'
        mode: 0644
        owner: root
        group: root
        force: yes
      become: yes

    - name: restart networking
      shell: "sleep 5 && reboot"
      become: yes
      async: 1
      poll: 0