- name: install software
  hosts: windows_workstations
  gather_facts: no
  tasks:
  - name: Install 7zip
    win_chocolatey:
      name: 7zip
      state: present

  - name: Install chrome
    win_chocolatey:
      name: Google_Chrome
      state: present

  - name: Install git
    win_chocolatey:
      name: Git
      state: present

  - name: Install Putty
    win_chocolatey:
      name: Putty
      state: present

  - name: Install notepad++
    win_chocolatey:
      name: Notepad++
      state: present

  - name: Install python3
    win_chocolatey:
      name: Pyton3
      state: present

  - name: Install visual studio code
    win_chocolatey:
      name: Visual Studio Code
      state: present